version: "3.8"
services:
  app:
    build: .
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/detecor
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: detecor
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data:
